added group caching feature
topcoder-platform/groups-api pull request #125
Opened 2022-12-23 08:02 UTC by bountyC0d3r

2022-12-23 09:08 UTC, ThomasKranitsas requested changes
When caching a group from `getGroup` we take into consideration the `includeSubGroups`/`includeParentGroups` filters. But, the next time we query for the same group ID, we return whatever is in the cache without checking those.

Example scenario:
- Request for group `A` without parent or sub groups
- The group is fetched from DB and cached
- Request for the same groups again from cache and also request sub groups
- The group is returned without sub groups as it's cached without sub groups

2022-12-23 13:50 UTC, ThomasKranitsas commented
@bountyC0d3r here's the ideal implementation IMHO:

```
Check cache, if data is in there, check if `sub` and/or `parent` groups are required, if required and not in cache, fetch from DB and update cache. Return data.
```

This way, we don't fetch unnecessary data for caching but we don't worry about data not being in cache as we're checking before we return it

2022-12-30 11:14 UTC, bountyC0d3r commented
@ThomasKranitsas incorporated the review comments, please check and approve if all is good

2023-01-05 10:14 UTC, ThomasKranitsas approved these changes

2023-01-05 10:16 UTC, merged